- name: Generate Living Documentation
  id: generate_living_doc
  uses: AbsaOSS/living-doc-generator@v0.2.0
  env:
    GITHUB_TOKEN: ${{ secrets.LIV_DOC_ACCESS_TOKEN }}  
  with:
    repositories: '[
      {
        "organization-name": "MobiTikula",
        "repository-name": "living-documentation-project-example",
        "query-labels": ["DocumentedFeature"],
        "projects-title-filter": []
      }
    ]'
    project-state-mining: true
    structured-output: false
    verbose-logging: true
    output-path: "./output"

    
